config/routes.rb
require 'resque/server'
require 'resque/scheduler/server'

Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  guisso_for :user
  root :to => 'home#index'

  get 'angular/*path' => 'home#angular_template'

  resources :connectors, except: [:show] do
    member do
      put 'poll'
    end

    collection do
      get 'google_spreadsheets_callback'
      get 'google_fusiontables_callback'
    end
  end

  scope :api do
    get 'connectors' => 'api#connectors'
    get 'reflect/connectors/:id(/*path)' => 'api#reflect', as: 'api_reflect', format: false

    scope :data do
      get    'connectors/:id(/*path)'  => 'api#query', as: 'api_data', format: false
      post   'connectors/:id(/*path)'  => 'api#insert'
      put    'connectors/:id(/*path)'  => 'api#update'
      delete 'connectors/:id(/*path)'  => 'api#delete'
    end

    get 'picker' => 'api#picker'
    post 'notify/connectors/:id/*path'=> 'api#notify', format: false
    post 'invoke/connectors/:id/*path' => 'api#invoke', format: false
    post 'callback/connectors/:id/*path' => 'api#callback', format: false
  end

  namespace :api, defaults: {format: :json}, format: false do
    resources :event_handlers, only: [:index, :create, :destroy]
  end

  resources :event_handlers
  resources :activities, only: :index

  mount Resque::Server.new, at: '/_resque', constraints: { ip: '127.0.0.1' }
end

app/models/connector.rb
class Connector < ActiveRecord::Base
  belongs_to :user
  has_many :event_handlers

  validates_presence_of :name
  validates_presence_of :guid

  def human_type
    type.to_s[0 .. -10].underscore.humanize.titleize
  end

  def label
    name
  end

  def has_events?
    true
  end

  def has_actions?
    true
  end

  before_validation :generate_guid

  default_scope { order('user_id desc, name') } # order first shared connectors and then by name

  abstract :url

  abstract def lookup(path, context)
  end

  abstract def callback(context, path, request)
  end

  store :settings

  def generate_guid
    self.guid ||= Guid.new.to_s
  end

  def connector
    self
  end

  def lookup_path(path, context)
    lookup path.to_s.split('/'), context
  end

  def self.with_optional_user(user)
    where('user_id = ? OR user_id is null', user.id)
  end

  def self.shared
    where('user_id is null')
  end

  def shared?
    user.nil?
  end

  def pollable?
    !self.event_handlers.where(poll: true).empty?
  end

  def needs_authorization?
    false
  end

  def has_notifiable_events?
    false
  end

  def generate_secret_token!
    token = Guid.new.to_s
    self.secret_token = BCrypt::Password.create(token)

    save!

    token
  end

  def authenticate_with_secret_token(token)
    BCrypt::Password.new(self.secret_token) == token
  end

  module NotifyJob
    def self.perform(connector_id, path, body)
      connector = Connector.find(connector_id)
      body = JSON.parse body
      subscribed_events = connector.event_handlers.where(event: path, enabled: true)
      subscribed_events.each do |event_handler|
        event_handler.trigger(body)
      end
    end
  end

  module PollJob
    def self.perform(connector_id)
      PoirotRails::Activity.start("Poll", connector_id: connector_id) do
        connector = Connector.find(connector_id)
        handlers_by_event = connector.event_handlers.where(poll: true, enabled: true).group_by do |handler|
          [handler.event, handler.user]
        end

        handlers_by_event.each do |(event_path, user), handlers|
          events = connector.lookup_path(event_path, RequestContext.new(user)).poll
          events.each do |event|
            handlers.each do |handler|
              PoirotRails::Activity.start("polling_event", event: event, handler_id: handler.id, user_id: handler.user_id, connector_id: connector_id, handled_event: handler.event, url: connector.url) do
                handler.trigger event
              end
            end
          end
        end
      end
    end
  end
end

app/controllers/connectors_controller.rb
class ConnectorsController < ApplicationController
  add_breadcrumb 'Connectors', :connectors_path

  # connectors can be edited. accessible_connectors are just listed
  expose(:accessible_connectors) { Connector.with_optional_user(current_user) }
  expose(:connectors) { current_user.connectors }
  expose(:connector) do
    if params[:id]
      connectors.find params[:id]
    else
      connector = (params[:type] || params[:connector][:type]).constantize.new
      connector.user_id = current_user.id
      connector
    end
  end

  def index
  end

  def new
    add_breadcrumb 'New connector'
  end

  def edit
    if connector.has_notifiable_events? && !connector.secret_token
      @secret_token = connector.generate_secret_token!
    end

    add_breadcrumb connector.name
  end

  def create
    if connector.needs_authorization?
      state = params.require(:connector).permit!.to_json
      redirect_to connector.authorization_uri(url_for(controller: 'connectors', action: connector.callback_action), state)
    else
      connector.update_attributes params.require(:connector).permit!
      if connector.save
        redirect_to connectors_path, notice: "Connector #{connector.name} successfully created."
      else
        render action: "new"
      end
    end
  end

  def update
    connector.update_attributes params.require(:connector).permit!
    if connector.save
      redirect_to connectors_path, notice: "Connector #{connector.name} successfully updated."
    else
      render action: "edit"
    end
  end

  def destroy
    connector.destroy
    redirect_to connectors_path, notice: "Connector #{connector.name} successfully deleted."
  end

  def google_fusiontables_callback
    params[:type] = "GoogleFusionTablesConnector"
    connector = self.connector

    api = GoogleFusionTablesConnector.api_client
    api.authorization.code = params[:code]
    api.authorization.redirect_uri = url_for(controller: 'connectors', action: connector.callback_action)
    access_token = api.authorization.fetch_access_token!

    connector.update_attributes JSON.parse(params[:state])
    connector.access_token = access_token["access_token"]
    connector.refresh_token = access_token["refresh_token"]
    connector.expires_at = access_token["expires_in"].seconds.from_now

    if connector.save
      redirect_to edit_connector_path(connector), notice: "Connector #{connector.name} successfully created."
    else
      render action: "new"
    end

  end


  def google_spreadsheets_callback
    # These two lines so we can reuse decent_exposure's logic
    params[:type] = "GoogleSpreadsheetsConnector"
    connector = self.connector

    api = GoogleSpreadsheetsConnector.api_client
    api.authorization.code = params[:code]
    api.authorization.redirect_uri = url_for(controller: 'connectors', action: connector.callback_action)
    access_token = api.authorization.fetch_access_token!

    connector.update_attributes JSON.parse(params[:state])
    connector.access_token = access_token["access_token"]
    connector.refresh_token = access_token["refresh_token"]
    connector.expires_at = access_token["expires_in"].seconds.from_now

    if connector.save
      redirect_to edit_connector_path(connector), notice: "Connector #{connector.name} successfully created."
    else
      render action: "new"
    end
  end

  def authorization_callback
    params[:type] = session[:connector_class_name]
    connector = self.connector

    connector.update_attributes session[:connector_params]

    session.delete :connector_class_name
    session.delete :connector_params

    connector.finish_authorization(params, authorization_callback_connectors_url)
    if connector.save
      redirect_to connectors_path, notice: "Connector #{connector.name} successfully created."
    else
      render action: "new"
    end
  end

  def poll
    connector = connector_from_guid()
    Connector::PollJob.perform(connector.id)
    redirect_to connectors_path, notice: "Connector #{connector.name} successfully polled."
  end

  private

  def connector_from_guid
    accessible_connectors.find_by_guid(params[:id])
  end
end

app/views/connectors/_form_act.haml
.field
  = f.label :url, "URL"
  = f.text_field :url, value: connector.url

.field
  = f.label :access_token, "Access token"
  = f.text_field :access_token, value: connector.access_token

app/views/connectors/_form_cdx.haml
.field
  = f.label :url, "Base API Url"
  = f.text_field :url, value: connector.url, placeholder: "http://cdx-host.com/api"

.field
  = f.label :oauth_token, "OAuth token"
  = f.text_field :oauth_token, value: connector.oauth_token

app/views/connectors/_form_elasticsearch.haml
.field
  = f.label :url, "URL"
  = f.text_field :url, value: connector.url

app/views/connectors/_form_elasticsearch_connector.haml
.field
  = f.label :url, "URL"
  = f.text_field :url, value: connector.url

app/views/connectors/_form_google_spreadsheets.haml
- if connector.persisted?
  :javascript
    var pickerApiLoaded = false;

    function onApiLoad() {
      gapi.load('picker', {'callback': function() { pickerApiLoaded = true }});
    }

    function createPicker() {
      if (pickerApiLoaded) {
        var picker = new google.picker.PickerBuilder().
            addView(new google.picker.DocsView(google.picker.ViewId.SPREADSHEETS).
              setMode(google.picker.DocsViewMode.LIST)).
            setAppId('#{Settings.google.app_id}').
            setDeveloperKey("#{Settings.google.browser_key}").
            setOAuthToken("#{connector.access_token}").
            setCallback(pickerCallback).
            build();
        picker.setVisible(true);
      }
    }

    function pickerCallback(data) {
      if (data[google.picker.Response.ACTION] == google.picker.Action.PICKED) {
        var doc = data[google.picker.Response.DOCUMENTS][0];
        $('#connector_spreadsheet_key').val(doc.id);
        $('#connector_spreadsheet_name').val(doc.name);
      }
    }

  .field
    = f.label :spreadsheet_name, "File"
    = f.text_field :spreadsheet_name, value: connector.spreadsheet_name, readonly: true, style: 'background-color: white'
    %button.btn{onclick: "javascript:createPicker(); return false;"} Choose
    = f.hidden_field :spreadsheet_key, value: connector.spreadsheet_key
  <script type="text/javascript" src="https://apis.google.com/js/api.js?onload=onApiLoad"></script>

app/views/connectors/_form_ona.haml
.field
  = f.label :url, "URL"
  = f.text_field :url, value: connector.url || "https://ona.io"
.field
  = f.label :auth_method, "Authentication method"
  %div.radio
    %label
      = f.radio_button :auth_method, "anonymous", checked: connector.auth_method == "anonymous"
      Anonymous
  %div.radio
    %label
      = f.radio_button :auth_method, "api_token", checked: connector.auth_method == "api_token"
      Api Token
      = f.text_field :api_token, value: connector.api_token

:javascript
  $(function() {
    function refresh() {
      $("#connector_api_token").prop('disabled', $("#connector_auth_method_anonymous").is(':checked'));
    }

    $("#connector_auth_method_anonymous, #connector_auth_method_api_token").change(refresh);
    refresh();
  });

app/views/connectors/_form_pollit.haml
.field
  = f.label :url, "URL"
  = f.text_field :url, value: connector.url
.field
  = f.label :username
  = f.text_field :username, value: connector.username
.field
  = f.label :password
  = f.password_field :password, value: connector.password

app/views/connectors/_form_rapid_pro.haml
.field
  = f.label :url, "URL"
  = f.text_field :url, value: connector.url || "https://rapidpro.io"
.field
  = f.label :token, "API Token"
  = f.text_field :token, value: connector.token

app/views/connectors/_form_resource_map.haml
.field
  = f.label :url, "URL"
  = f.text_field :url, value: connector.url || "https://resourcemap.instedd.org"
.field
  = f.label :username
  = f.text_field :username, value: connector.username
.field
  = f.label :password
  = f.password_field :password, value: connector.password

app/views/connectors/_form_verboice.haml
.field
  = f.label :url, "URL"
  = f.text_field :url, value: connector.url || "https://verboice.instedd.org"
.field
  = f.label :username
  = f.text_field :username, value: connector.username
.field
  = f.label :password
  = f.password_field :password, value: connector.password

app/views/connectors/edit.haml
%h4 Edit '#{connector.name}' connector

= render 'form'

%hr

%ul
  %li GUID: #{connector.guid}
  %li= link_to "Reflect", api_reflect_path(connector.guid)
  - if @secret_token
    %li Secret token: #{@secret_token}

app/views/connectors/google_spreadsheets_callabck.erb
<script type="text/javascript">
  var developerKey = '<%= Settings.google.browser_key %>';
  var clientId = '<%= Settings.google.client_id %>';
  var scope = ['https://www.googleapis.com/auth/drive.file'];

  var pickerApiLoaded = false;
  var oauthToken;

  // Use the API Loader script to load google.picker and gapi.auth.
  function onApiLoad() {
    gapi.load('auth');
    gapi.load('picker', {'callback': onPickerApiLoad});
  }

  function onAuthApiLoad() {
    window.gapi.auth.authorize(
        {
          'client_id': clientId,
          'scope': scope,
          'immediate': false
        },
        handleAuthResult);
  }

  function onPickerApiLoad() {
    pickerApiLoaded = true;
    // createPicker();
  }

  function handleAuthResult(authResult) {
    if (authResult && !authResult.error) {
      // console.log(authResult);
      // oauthToken = authResult.access_token;
      oauthToken = "ya29.xAAefCuJICbH4NrDTDimG0N6FhTVo7cWrPnpS0CVcj89NLGgGivGblx5wpOeYIDb-Kr3cyO2YWyo1w";
      createPicker();
    }
  }

  // Create and render a Picker object for picking user Photos.
  function createPicker() {
    if (pickerApiLoaded) {
      var picker = new google.picker.PickerBuilder().
          addView(google.picker.ViewId.SPREADSHEETS).
          setOAuthToken("ya29.xAAefCuJICbH4NrDTDimG0N6FhTVo7cWrPnpS0CVcj89NLGgGivGblx5wpOeYIDb-Kr3cyO2YWyo1w").
          setDeveloperKey(developerKey).
          setCallback(pickerCallback).
          setAppId('813633885570').
          build();
      picker.setVisible(true);
    }
  }

  // A simple callback implementation.
  function pickerCallback(data) {
    var url = 'nothing';
    if (data[google.picker.Response.ACTION] == google.picker.Action.PICKED) {
      debugger;
      var doc = data[google.picker.Response.DOCUMENTS][0];
      url = doc[google.picker.Document.URL];
    }
    var message = 'You picked: ' + url;
    document.getElementById('result').innerHTML = message;
  }
</script>
<div id="result"></div>
<a href="javascript:createPicker()">CLICK</a>
<script type="text/javascript" src="https://apis.google.com/js/api.js?onload=onApiLoad"></script>

app/views/connectors/index.haml
.row-fluid
  .span12
    %h4 Connectors
    - accessible_connectors.each do |connector|
      .row-fluid
        .span12.box-list
          - if connector.shared?
            = connector.name
            (Shared)
            = link_to "Reflect", api_reflect_path(connector.guid)
          - else
            = icon_link_to :'icf-arrow', connector.name, edit_connector_path(connector)

          - if connector.pollable?
            = link_to "Poll", "/connectors/#{connector.guid}/poll", method: :put

    - %w(ACT CDX Elasticsearch GoogleSpreadsheets GoogleFusionTables MBuilder ONA Pollit RapidPro Remindem ResourceMap Verboice).each do |name|
      = icon_link_to :'icc-add', "Add #{connector_human_name_for_type(name)} Connector", new_connector_path(type: "#{name}Connector"), class: "add-connector blue"
      %br
      %br

app/views/connectors/new.haml
%h2 New #{connector.human_type} connector

= render "form"