config/routes.rb
require 'resque/server'
require 'resque/scheduler/server'

Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  guisso_for :user
  root :to => 'home#index'

  get 'angular/*path' => 'home#angular_template'

  resources :connectors, except: [:show] do
    member do
      put 'poll'
    end

    collection do
      get 'google_spreadsheets_callback'
      get 'google_fusiontables_callback'
    end
  end

  scope :api do
    get 'connectors' => 'api#connectors'
    get 'reflect/connectors/:id(/*path)' => 'api#reflect', as: 'api_reflect', format: false

    scope :data do
      get    'connectors/:id(/*path)'  => 'api#query', as: 'api_data', format: false
      post   'connectors/:id(/*path)'  => 'api#insert'
      put    'connectors/:id(/*path)'  => 'api#update'
      delete 'connectors/:id(/*path)'  => 'api#delete'
    end

    get 'picker' => 'api#picker'
    post 'notify/connectors/:id/*path'=> 'api#notify', format: false
    post 'invoke/connectors/:id/*path' => 'api#invoke', format: false
    post 'callback/connectors/:id/*path' => 'api#callback', format: false
  end

  namespace :api, defaults: {format: :json}, format: false do
    resources :event_handlers, only: [:index, :create, :destroy]
  end

  resources :event_handlers
  resources :activities, only: :index

  mount Resque::Server.new, at: '/_resque', constraints: { ip: '127.0.0.1' }
end

app/models/event_handler.rb
class EventHandler < ActiveRecord::Base
  belongs_to :connector
  belongs_to :user
  belongs_to :target_connector, class_name: 'Connector', foreign_key: 'target_connector_id'
  serialize :binding

  after_create :notify_action_created
  after_update :notify_action_updated
  after_create :notify_event_subscribe
  before_update :notify_event_update
  after_destroy :notify_event_unsubscribe

  module QueuePollJob
    def self.perform
      connector_ids = EventHandler.where(poll: true).distinct.pluck(:connector_id)
      connector_ids.each do |connector_id|
        Resque.enqueue_to(:hub, Connector::PollJob, connector_id)
      end
    end
  end

  def trigger(data)
    begin
      context = RequestContext.new(user)
      target_action = target_connector.lookup_path(action, context)
      PoirotRails::Activity.start("Action invoked", target_action: target_action.path, data: data) do
        target_action.invoke bind_event_data(data), context
      end
    rescue Exception => e
      logger.error "Error triggering event handler: #{e}"
    end
  end

  private

  def bind_event_data(data)
    @mapper ||= JsonMapper.new(binding || [])
    @mapper.map data
  end

  def notify_action_created
    target_action = target_connector.lookup_path(action, RequestContext.new(user))
    if target_action.respond_to?(:after_create)
      target_action.after_create(self.binding)
    end
  end

  def notify_action_updated
    target_action = target_connector.lookup_path(action, RequestContext.new(user))
    if target_action.respond_to?(:after_update)
      target_action.after_update(self.binding)
    end
  end

  def notify_event_subscribe
    context = RequestContext.new(user)
    source_event = connector.lookup_path(event, context)
    source_event.subscribe(context)
  end

  def notify_event_update
    return unless event_changed?

    context = RequestContext.new(user)
    if event_was
      old_event = connector.lookup_path(event_was, context)
      old_event.unsubscribe(context)
    end

    if event
      new_event = connector.lookup_path(event, context)
      new_event.subscribe(context)
    end
  end

  def notify_event_unsubscribe
    context = RequestContext.new(user)
    source_event = connector.lookup_path(event, context)
    source_event.unsubscribe(context)
  end
end

app/controllers/api/event_handlers_controller.rb
class Api::EventHandlersController < BaseApiController

  before_filter :authenticate_api_user!

  expose(:connectors) { Connector.with_optional_user(current_user) }
  expose(:event_handlers) { current_user.event_handlers }
  expose(:event_handler)

  def index
    render layout: false
  end

  def create
    event = connectors.find_by_guid(params[:event_handler][:event][:connector]).lookup_path(params[:event_handler][:event][:path], request_context)
    action = connectors.find_by_guid(params[:event_handler][:action][:connector]).lookup_path(params[:event_handler][:action][:path], request_context)

    event_handler = event.create(action, params[:event_handler][:binding], request_context)
    event_handler.name = params[:event_handler][:name]
    event_handler.enabled = params[:event_handler][:enabled]

    if event_handler.save
      render json: {success: true, id: event_handler.id}
    else
      render json: {success: false, errors: event_handler.errors.messages}
    end
  end

  def destroy
    event_handler.destroy
    render json: {success: true}
  end

end

app/controllers/event_handlers_controller.rb
class EventHandlersController < ApplicationController
  add_breadcrumb 'Tasks', :event_handlers_path

  expose(:event_handlers) { current_user.event_handlers.order(:id) }
  expose(:event_handler)

  def index
    add_breadcrumb 'New task'
  end

  def new
    add_breadcrumb 'New task'
  end

  def edit
    add_breadcrumb event_handler.name
  end

  def create
    load_view_models_params
    event_handler = @param_event.create(@param_action, @param_binding, request_context)
    event_handler.name = params[:event_handler][:name]
    if event_handler.save
      redirect_to event_handlers_path, notice: "Task #{event_handler.name} successfully created."
    else
      render action: "new"
    end
  end

  def update
    event_handler.update_attributes params.require(:event_handler).permit!
    update_from_view_models_params
    if event_handler.save
      redirect_to event_handlers_path, notice: "Task #{event_handler.name} successfully updated."
    else
      render action: "edit"
    end
  end

  def destroy
    event_handler.destroy
    redirect_to event_handlers_path, notice: "Task #{event_handler.name} successfully deleted."
  end

  protected

  def load_view_models_params
    @param_event = resolve_reference(JSON.parse(params[:task][:event]))
    @param_action = resolve_reference(JSON.parse(params[:task][:action]))
    @param_binding = JSON.parse(params[:task][:binding])
  end

  def update_from_view_models_params
    load_view_models_params

    if @param_event
      event_handler.connector = @param_event.connector
      event_handler.event = @param_event.path
    end

    if @param_action
      event_handler.target_connector = @param_action.connector
      event_handler.action = @param_action.path
    end

    event_handler.binding = @param_binding
  end

  def resolve_reference(event_or_action)
    if event_or_action["connector"].present? && event_or_action["path"].present?
      Connector.with_optional_user(current_user).find_by_guid(event_or_action["connector"]).lookup_path(event_or_action["path"], request_context)
    else
      nil
    end
  end
end

app/views/event_handlers/_form.haml
%div{'ng-app'=>'CreateTaskApp', 'ng-init' => init_scope(event: {connector: event_handler.connector.try(:guid), path: event_handler.event}, action: {connector: event_handler.target_connector.try(:guid), path: event_handler.action}, binding: event_handler.binding, name: event_handler.name)}

  %div(ng-controller='CreateTaskCtrl')
    = form_for(event_handler, html: {name: 'taskForm'}) do |f|
      %input(type='hidden' name='task[event]' value='{{event_json}}' ng-model="event" required='true')
      %input(type='hidden' name='task[action]' value='{{action_json}}' ng-model="action" required='true')
      %input(type='hidden' name='task[binding]' value='{{binding_json}}' ng-model="binding" required='true')

      - if event_handler.errors.any?
        .row-fluid
          .span12
            #error_explanation
              %h2
                = pluralize(event_handler.errors.count, "error")
                prohibited this task from being saved:
              %ul
                - event_handler.errors.full_messages.each do |msg|
                  %li= msg
      .row-fluid
        .span12
          .field
            = f.label :name
            = f.text_field :name, 'ng-model' => 'name', required: true
          .checkbox
            %label
              = f.check_box :enabled
              Enabled

      .row-fluid
        .span6
          %h2 Event

          %ih-entity-picker(model='event' type='event')
          %ih-source-box(model='event_reflect.args')

        .span6
          %h2 Action

          %ih-entity-picker(model='action' type='action' on-change='updateBinding()')

          %ih-target-box(model='binding' schema='action_reflect.args')

      .row-fluid
        .span12
          .actions
            %hr
              - if event_handler.new_record?
                %button.btn{:type => "submit", 'ng-disabled' => '!taskForm.$valid'} Save
              - else
                %button.btn{:type => "submit"} Update
                = icon_link_to :'icf-delete', 'Delete this task', event_handler_path(event_handler), method: :delete, :'data-confirm' => "Are you sure you want to delete this task?", class: "pull-right"

app/views/event_handlers/edit.haml
%h4 Edit '#{event_handler.name}'

= render 'form'

app/views/event_handlers/index.haml
.row-fluid
  .span12
    %h4 Tasks
    - event_handlers.each do |event_handler|
      .row-fluid
        .span12.box-list.task{class: event_handler.enabled? ? nil : "disabled"}
          - name = event_handler.name
          = icon_link_to :'icf-arrow', name, edit_event_handler_path(event_handler)

    = icon_link_to :'icc-add', "Add Task", new_event_handler_path, class: "blue"
    %br
    %br

app/views/event_handlers/new.haml
%h2 New task

= render "form"