config/routes.rb
require 'resque/server'
require 'resque/scheduler/server'

Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  guisso_for :user
  root :to => 'home#index'

  get 'angular/*path' => 'home#angular_template'

  resources :connectors, except: [:show] do
    member do
      put 'poll'
    end

    collection do
      get 'google_spreadsheets_callback'
      get 'google_fusiontables_callback'
    end
  end

  scope :api do
    get 'connectors' => 'api#connectors'
    get 'reflect/connectors/:id(/*path)' => 'api#reflect', as: 'api_reflect', format: false

    scope :data do
      get    'connectors/:id(/*path)'  => 'api#query', as: 'api_data', format: false
      post   'connectors/:id(/*path)'  => 'api#insert'
      put    'connectors/:id(/*path)'  => 'api#update'
      delete 'connectors/:id(/*path)'  => 'api#delete'
    end

    get 'picker' => 'api#picker'
    post 'notify/connectors/:id/*path'=> 'api#notify', format: false
    post 'invoke/connectors/:id/*path' => 'api#invoke', format: false
    post 'callback/connectors/:id/*path' => 'api#callback', format: false
  end

  namespace :api, defaults: {format: :json}, format: false do
    resources :event_handlers, only: [:index, :create, :destroy]
  end

  resources :event_handlers
  resources :activities, only: :index

  mount Resque::Server.new, at: '/_resque', constraints: { ip: '127.0.0.1' }
end

app/views/layouts/application.haml
- content_for :html_title do
  InSTEDD Platform datasets and actions integrations

- content_for :app_name do
  InSTEDD HUB

- content_for :app_logo do
  = image_tag "instedd-bootstrap/header/logos/guisso.png"

- content_for :app_version do
  = Hub::Application.config.version_name

- top_nav_bar do
  - top_nav_bar_item 'Home', root_path
  - if current_user
    - top_nav_bar_item 'Connectors', connectors_path, (params[:controller] == 'connectors')
    - top_nav_bar_item 'Tasks', event_handlers_path, (params[:controller] == 'event_handlers')
    - top_nav_bar_item 'Activity', activities_path, (params[:controller] == 'activities') if Activity.enabled?

= render template: 'instedd/application'